### ISSUE TITLE
Renderscrip Support mode

### ISSUE THREAD

**Issue by panzerdev** [500px/500px-android-blur#1]
Was Renderscript Support mode tried? it's v8 and easy to enable in the build script

defaultConfig{
..
renderscriptTargetApi 21
renderscriptSupportModeEnabled true
..
}

http://developer.android.com/tools/support-library/features.html#v8

**Comment by luojun** [comment]
Thanks for the suggestion and the contribution! Your PR has been merged. (Wasn't able to test it on API level 15 devices, yet. Will try when there's an available device. Test on emulator with API level 15 resulted in a crash in RenderScript.)

**Comment by panzerdev** [comment]
I had crashes in the emulator as well. This is why I flashed my Galaxy Nexus back with the 4.0.4 factory image and developed with that device as a target.
