### ISSUE TITLE
Problem when minifyEnabled=true

### ISSUE THREAD

**Issue by rmprosser** [500px/500px-android-blur#14]
When I use proguard with minifyEnabled option I get this fatal crash on launch:

`java.lang.RuntimeException: Unable to start activity ComponentInfo{...}: android.view.InflateException: Binary XML file line #67: Error inflating class com.fivehundredpx.android.blur.BlurringView`

But with minifyEnabled turned off, it works fine.

Are there any proguard rules I need to add?

**Comment by AndrazP** [comment]
Add:

```
-keep class android.support.v8.renderscript.** { *; }
```

to your proguard file.

**Comment by rmprosser** [comment]
Thank you, that works
