### ISSUE TITLE
Is it possible to use on SurfaceView?

### ISSUE THREAD

**Issue by lushan1314** [500px/500px-android-blur#31]
I want use on a MediaPlayer,but it is a Surface.

and i can't linsten the frame changed.

**Comment by yanayzimran** [comment]
I tried using it on a surfaceView as well (camera preview), but it doesn't work

**Comment by mlostekk** [comment]
same here.. was not able to get it to work

**Comment by StaticCoder** [comment]
it is scarcely possible to work on surfaceview，please give up
